name: Build Android APK
on: [push]
jobs:
  build:
    # Using 22.04 because it has the libraries (libtinfo5) that Buildozer needs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer cython virtualenv

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Automatically accept Android licenses
          yes | buildozer android signatures || true
          # Run the build and bypass the root user warning
          buildozer --warn_on_root=0 android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GestureApp-APK
          path: bin/*.apk
